default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root_aipd
  password: bolang009
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: aipd_spm_development

test:
  <<: *default
  database: aipd_spm_development

production:
  <<: *default
  database: aipd_spm_development
